/**
 * Ground material with patina PBR textures.
 *
 * Uses KTX2 textures generated by fal.ai Patina:
 *   - basecolor.ktx2: weathered copper/verdigris color
 *   - normal.ktx2: surface bumps and corrosion pits
 *   - roughness.ktx2: smooth vs rough variation
 *   - metalness.ktx2: bare metal vs oxidized
 *   - height.ktx2: depth detail for parallax
 *
 * Additional effects:
 *   - Caustics: noise-based dancing light patterns on the ground
 *   - Depth fog: fade ground toward water body color based on depth
 *     Shallow edges show patina clearly, deep center fades to navy
 *
 * The ground is a circle geometry below the water plane.
 */

// TODO: Load KTX2 textures with KTX2Loader
// TODO: Create MeshStandardNodeMaterial with PBR maps
// TODO: Add caustics as emissive overlay (scrolling noise, like reference)
// TODO: Add depth fog: mix ground color toward water color based on Y depth
